/* OSHA 30 Construction — Final Exam: 100 Questions (5 per module) */
const EXAM_QUESTIONS = [
  /* ── Module 1: Introduction to OSHA ── */
  { q:"Which agency conducts research and recommends occupational safety standards, but does NOT enforce them?", options:["OSHA","NIOSH","EPA","Department of Labor"], a:1, explain:"NIOSH (National Institute for Occupational Safety and Health) conducts research and makes recommendations. OSHA enforces standards.", moduleRef:1, moduleName:"Intro to OSHA" },
  { q:"An employer receives an OSHA citation. How many working days does the employer have to contest it?", options:["7 working days","10 working days","15 working days","30 calendar days"], a:2, explain:"Employers have 15 working days from receipt of a citation to file a Notice of Contest with OSHA.", moduleRef:1, moduleName:"Intro to OSHA" },
  { q:"Three workers at a site require in-patient hospitalization after a chemical release. The employer must report this to OSHA within:", options:["1 hour","8 hours","24 hours","72 hours"], a:2, explain:"Work-related in-patient hospitalizations of 3 or more workers must be reported to OSHA within 24 hours. Fatalities must be reported within 8 hours.", moduleRef:1, moduleName:"Intro to OSHA" },
  { q:"A State Plan must be:", options:["Identical to federal OSHA standards","At least as effective as federal OSHA standards","More strict than federal OSHA in all areas","Approved by the Governor of the state"], a:1, explain:"State Plans must be at least as effective as federal OSHA. They may be more stringent, but cannot be less protective.", moduleRef:1, moduleName:"Intro to OSHA" },
  { q:"The General Duty Clause (Section 5(a)(1)) applies when:", options:["A specific OSHA standard exists for the hazard","No specific OSHA standard addresses the hazard, but it is recognized and likely to cause death or serious harm","A worker files a formal complaint","An employer has more than 10 employees"], a:1, explain:"The General Duty Clause covers recognized hazards not addressed by a specific standard. OSHA uses it to cite employers for serious hazards even without a specific regulation.", moduleRef:1, moduleName:"Intro to OSHA" },

  /* ── Module 2: Managing Safety & Health ── */
  { q:"An OSHA 300A annual summary must be certified by:", options:["Any safety professional","A company executive","An OSHA compliance officer","The site's competent person"], a:1, explain:"The OSHA 300A must be certified by a company executive (owner, officer, director, or highest-ranking company official at the establishment).", moduleRef:2, moduleName:"Safety Programs" },
  { q:"Which control is MORE effective than wearing hearing protection to address noise?", options:["Administrative controls such as job rotation","Engineering controls such as noise enclosures","Providing employees with higher-rated hearing protection","Conducting more frequent audiometric testing"], a:1, explain:"The hierarchy of controls rates engineering controls above administrative controls and PPE. An enclosure that reduces noise at the source is more effective than rotation or PPE.", moduleRef:2, moduleName:"Safety Programs" },
  { q:"A near-miss incident should be:", options:["Ignored if no injury occurred","Reported and investigated to prevent future incidents","Reported only if it involved equipment valued over $10,000","Documented only if witnessed by a supervisor"], a:1, explain:"Near-misses must be reported and investigated. They reveal hazards before someone is hurt — the same root causes that led to the near-miss can cause a fatality next time.", moduleRef:2, moduleName:"Safety Programs" },
  { q:"A worker slips on ice, twists their knee, and their doctor prescribes prescription-strength anti-inflammatories and 3 days of modified duty. This incident is:", options:["Not recordable — first aid only","Recordable — prescription medication and restricted duty both make it recordable","Recordable only because of the restricted duty","Not recordable — ice is a weather event, not a work hazard"], a:1, explain:"Any work-related injury requiring prescription medication OR resulting in restricted work/days away from work is OSHA-recordable. Both conditions exist here.", moduleRef:2, moduleName:"Safety Programs" },
  { q:"The primary purpose of a Job Hazard Analysis (JHA) is to:", options:["Assign blame after an accident","Document OSHA compliance","Identify and control hazards BEFORE a task begins","Satisfy insurance requirements"], a:2, explain:"A JHA proactively breaks a job into steps, identifies hazards in each step, and recommends controls before work begins — preventing incidents rather than reacting to them.", moduleRef:2, moduleName:"Safety Programs" },

  /* ── Module 3: Fall Hazards ── */
  { q:"A worker on a residential roof is at 8 feet above grade. Fall protection is:", options:["Not required below 10 feet","Required — 6-foot threshold applies to all construction","Required only if the slope exceeds 4:12","Required only if there are no parapets"], a:1, explain:"The 6-foot threshold for fall protection applies to all construction work, including residential roofing. There is no exception for 'low' slopes or short heights below 10 feet in construction.", moduleRef:3, moduleName:"Fall Hazards" },
  { q:"The total fall distance using a PFAS (free fall + deceleration) must not result in:", options:["Free fall exceeding 3 feet","The worker contacting the lower level or obstruction below","Deceleration forces over 900 lbs","Swing falls of more than 15 feet"], a:1, explain:"The critical requirement is that the total fall distance (free fall ≤6 ft + deceleration ≤3.5 ft = up to 9.5 ft total) must not result in the worker hitting the lower level or any obstruction.", moduleRef:3, moduleName:"Fall Hazards" },
  { q:"A floor opening 18 inches wide and 24 inches long must be:", options:["Covered, secured, and marked — openings ≥2 inches require covers","Left open if it will be in use within 4 hours","Guarded with a 36-inch high rope barrier","Covered only if adjacent to a walking surface"], a:0, explain:"Holes 2 inches or more in any dimension must be covered with material that supports at least twice the maximum load, secured against displacement, and marked 'HOLE' or 'COVER'.", moduleRef:3, moduleName:"Fall Hazards" },
  { q:"What is the maximum arresting force allowed on a worker's body during a fall arrest?", options:["900 lbs","1,800 lbs","3,600 lbs","5,000 lbs"], a:1, explain:"PFAS must limit the arresting force on the worker's body to no more than 1,800 lbs. Forces above this level can cause serious internal injuries even if the fall is stopped.", moduleRef:3, moduleName:"Fall Hazards" },
  { q:"A worker is installing a new guardrail on a leading edge and PFAS cannot be used safely. The employer must:", options:["Waive fall protection since PFAS is infeasible","Develop and implement a written fall protection plan, designed by a qualified person","Allow the work to proceed with a warning line only","Stop work until PFAS is feasible"], a:1, explain:"When conventional fall protection (guardrails, safety nets, PFAS) is infeasible at leading edges, a written fall protection plan developed by a qualified person must be implemented.", moduleRef:3, moduleName:"Fall Hazards" },

  /* ── Module 4: Electrical Hazards ── */
  { q:"A construction crew is working with a crane near power lines. The lines are rated at 115kV. What is the minimum required clearance?", options:["10 feet","15 feet","20 feet","25 feet"], a:1, explain:"For voltages between 50.1kV and 200kV, the required minimum clearance is 15 feet. The 10-foot rule only applies to voltages up to 50kV.", moduleRef:4, moduleName:"Electrical" },
  { q:"Which of the following is an acceptable alternative to GFCI protection on a construction site?", options:["Using only double-insulated tools","The Assured Equipment Grounding Conductor Program (AEGCP)","Grounding all equipment to the building frame","Using only battery-powered tools"], a:1, explain:"The AEGCP is the OSHA-approved alternative to GFCI. It requires a written program, visual inspection before each use, and scheduled electrical testing of cords and receptacles.", moduleRef:4, moduleName:"Electrical" },
  { q:"The primary purpose of a GFCI device is to protect against:", options:["Overloading a circuit","Short circuits in fixed wiring","Ground faults that could cause electrocution","Power surges that could damage equipment"], a:2, explain:"GFCIs detect ground faults — leakage of current to ground through a person — and trip within 1/40th of a second, before the current can cause ventricular fibrillation.", moduleRef:4, moduleName:"Electrical" },
  { q:"An employee contacts an overhead power line while operating a backhoe. The operator should:", options:["Immediately jump from the cab and run","Stay in the cab and call for help; do not allow anyone to approach","Jump from the cab and shuffle away with feet together","Reverse the machine to break contact, then exit normally"], a:1, explain:"Stay in the cab — it acts as a Faraday cage protecting the operator from electrocution. Ground workers must stay back at least 300 feet or the span of the wire — the ground may be energized.", moduleRef:4, moduleName:"Electrical" },
  { q:"During a Lockout/Tagout procedure, after applying the lockout device, the next step is:", options:["Begin work immediately","Notify the supervisor","Release or restrain all stored/residual energy and verify de-energization","Post a warning sign on the equipment"], a:2, explain:"After applying lockout devices, all stored/residual energy (capacitors, springs, gravity, hydraulics) must be released or restrained, and the equipment tested to verify it cannot be started.", moduleRef:4, moduleName:"Electrical" },

  /* ── Module 5: Struck-By ── */
  { q:"A worker is hit by a concrete block that falls from a scaffold two floors above. This is classified as a:", options:["Caught-in/between hazard","Falling object struck-by hazard","Flying object struck-by hazard","Swinging object struck-by hazard"], a:1, explain:"A falling object struck-by hazard involves objects dropped or knocked from an elevated work surface. The block falling from the scaffold above strikes the worker below.", moduleRef:5, moduleName:"Struck-By" },
  { q:"During roadway construction, what is the minimum class of high-visibility apparel required for workers?", options:["Class 1","Class 2","Class 3","No specific class — any bright color"], a:1, explain:"ANSI/ISEA 107 Class 2 is the minimum required for roadway work zones. Class 3 is required in high-traffic or nighttime conditions.", moduleRef:5, moduleName:"Struck-By" },
  { q:"Which of the following is NOT a method to protect workers from falling objects?", options:["Toeboards on scaffolding","Tool lanyards on elevated tools","Canopies over walkways","Increased lighting in the work area"], a:3, explain:"Toeboards, tool lanyards, canopies, and debris nets all physically prevent or catch falling objects. Increased lighting improves visibility but does not prevent objects from falling.", moduleRef:5, moduleName:"Struck-By" },
  { q:"A driver of a concrete truck backs up on a busy construction site. The driver's view to the rear is partially blocked. The driver must:", options:["Use mirrors only and proceed slowly","Have a designated spotter in position before backing","Sound the horn twice and back up carefully","Stop work until a backup camera is installed"], a:1, explain:"When a vehicle operator's view is obstructed, a spotter must be used during backing maneuvers. The spotter and operator must use prearranged signals and maintain visual contact.", moduleRef:5, moduleName:"Struck-By" },
  { q:"A worker using a powder-actuated nail gun accidentally fires a nail that strikes a coworker in the leg. This is classified as:", options:["A falling object hazard","A flying object struck-by hazard","A caught-in/between hazard","An electrical hazard"], a:1, explain:"A nail propelled by a powder-actuated tool and striking a worker is a flying object struck-by hazard. Only trained and certified workers may use powder-actuated tools.", moduleRef:5, moduleName:"Struck-By" },

  /* ── Module 6: Caught-In/Between ── */
  { q:"A worker's glove is caught in a rotating drill and pulls their hand into the machine. This is an example of:", options:["A shear point hazard","A wrap point hazard","A pinch point hazard","A struck-by hazard"], a:1, explain:"A wrap point involves a rotating shaft or part that catches clothing, gloves, or hair and wraps it around the rotating element, pulling the worker into the machine.", moduleRef:6, moduleName:"Caught-In" },
  { q:"A Type B soil excavation is 8 feet deep. The wall protection must include a slope of no steeper than:", options:["53° (¾:1 H:V)","45° (1:1 H:V)","34° (1½:1 H:V)","Shoring only — no sloping allowed"], a:1, explain:"Type B soil requires a maximum slope of 1:1 (1 foot horizontal for every 1 foot vertical), which equals 45 degrees. More aggressive slopes are only permissible in Type A soil.", moduleRef:6, moduleName:"Caught-In" },
  { q:"An interlocked machine guard:", options:["Can be bypassed temporarily during cleaning","Automatically shuts off the machine when the guard is opened","Must be manually activated by the operator","Is only required on saws and cutting tools"], a:1, explain:"An interlocked guard is connected to the machine's power system so the machine cannot operate (or automatically stops) when the guard is opened or removed — preventing access to dangerous parts during operation.", moduleRef:6, moduleName:"Caught-In" },
  { q:"Benching is NOT an acceptable protective system for:", options:["Type A soil","Type B soil only","Type C soil","Any soil deeper than 5 feet"], a:2, explain:"Benching is prohibited in Type C soil because it is too unstable to maintain the step-shaped cuts. Type C soil requires sloping, shoring, or shielding.", moduleRef:6, moduleName:"Caught-In" },
  { q:"The best way to prevent caught-in/between injuries from machinery is:", options:["Require all workers to wear close-fitting clothing","Install and maintain all required machine guards in place","Limit machine use to only trained operators","Train workers to recognize rotating equipment"], a:1, explain:"Installing and maintaining machine guards as required by OSHA is the primary engineering control for caught-in/between hazards. Guards must always be in place during operation.", moduleRef:6, moduleName:"Caught-In" },

  /* ── Module 7: PPE ── */
  { q:"A worker doing demolition near energized equipment at 6,600 volts needs a hard hat. Which class is REQUIRED?", options:["Class C — general use","Class G — General; rated 2,200V","Class E — Electrical; rated 20,000V","Either Class G or E will suffice"], a:2, explain:"Class G hard hats are only rated to 2,200 volts — insufficient for 6,600V. Class E (Electrical) hard hats are rated to 20,000 volts and must be used.", moduleRef:7, moduleName:"PPE" },
  { q:"A worker's hearing protection has a labeled NRR of 30 dB. Using OSHA's method, the estimated real-world noise reduction is approximately:", options:["30 dB","23 dB","15 dB","8.5 dB"], a:3, explain:"OSHA's simplified method: (NRR – 7) ÷ 2 = (30 – 7) ÷ 2 = 11.5 dB. Alternatively, halving the NRR gives ~15 dB. OSHA's method = 8.5 dB effective reduction.", moduleRef:7, moduleName:"PPE" },
  { q:"A worker must wear a tight-fitting half-face respirator. Before wearing it for the first time, they must:", options:["Complete a 1-hour safety training","Pass a medical evaluation and quantitative fit test","Have their supervisor verify the respirator fits","Pass an annual physical exam"], a:1, explain:"29 CFR 1910.134 requires a medical evaluation by a healthcare provider BEFORE a worker is fit-tested or uses a tight-fitting respirator for the first time.", moduleRef:7, moduleName:"PPE" },
  { q:"ANSI/ISEA Z87.1 is the standard for:", options:["Head protection","Eye and face protection","Foot protection","High-visibility garments"], a:1, explain:"ANSI/ISEA Z87.1 is the American standard for eye and face protective devices, including safety glasses, goggles, and face shields. Hard hats are covered by ANSI Z89.1.", moduleRef:7, moduleName:"PPE" },
  { q:"An employer must provide required PPE to workers at:", options:["A subsidized cost workers can afford","No cost to workers, with limited exceptions","The worker's expense if they lose it","Cost-sharing with workers, 50/50"], a:1, explain:"OSHA requires employers to provide most required PPE at no cost to workers. Exceptions include non-specialty safety-toe footwear and prescription safety glasses used outside the workplace.", moduleRef:7, moduleName:"PPE" },

  /* ── Module 8: Health Hazards ── */
  { q:"A construction worker is sanding painted surfaces in a pre-1978 building without a respirator. The primary health concern is:", options:["Asbestos exposure","Lead dust inhalation","Silica dust inhalation","Solvent vapor exposure"], a:1, explain:"Paint in pre-1978 buildings may contain lead. Sanding, grinding, or disturbing lead-based paint generates lead dust — the PEL is 50 μg/m³ and medical surveillance begins at the 30 μg/m³ action level.", moduleRef:8, moduleName:"Health Hazards" },
  { q:"Which section of an SDS contains information on required PPE and exposure controls?", options:["Section 2","Section 4","Section 8","Section 11"], a:2, explain:"Section 8 of the SDS contains exposure limits, engineering controls, and required PPE. Section 2 covers hazard identification; Section 4 covers first aid; Section 11 covers toxicological information.", moduleRef:8, moduleName:"Health Hazards" },
  { q:"A concrete cutting saw operator works 8 hours per day. The silica action level that triggers medical surveillance is:", options:["100 μg/m³","50 μg/m³","25 μg/m³","10 μg/m³"], a:2, explain:"The silica action level is 25 μg/m³ as an 8-hour TWA. At or above this level, employers must offer medical surveillance, enhanced exposure monitoring, and other program elements.", moduleRef:8, moduleName:"Health Hazards" },
  { q:"The 9 GHS pictograms are bordered by what color diamond?", options:["Orange","Yellow","Red","Black"], a:2, explain:"GHS pictograms have a red diamond border. The symbol inside (flame, skull, corrosion, etc.) indicates the type of hazard. Red is used specifically to indicate that the pictogram is a GHS label element.", moduleRef:8, moduleName:"Health Hazards" },
  { q:"A worker develops a rash after prolonged skin contact with wet cement. This is caused by:", options:["Silica dust penetrating the skin","The high alkalinity of cement (pH ~12.5)","The aggregate particles in the mix","UV degradation of cement additives"], a:1, explain:"Wet cement has a pH of approximately 12.5, which is highly alkaline. Prolonged skin contact causes alkali chemical burns (cement dermatitis). Workers must wear gloves and protective clothing.", moduleRef:8, moduleName:"Health Hazards" },

  /* ── Module 9: Stairways & Ladders ── */
  { q:"A job-site trailer is elevated 24 inches above grade. OSHA requires:", options:["No access equipment — 24 inches is below the threshold","A stairway or ladder — the 19-inch threshold is exceeded","Only a step or block — no ladder required under 36 inches","A ramp rated for the load"], a:1, explain:"Stairways or ladders are required at every point where there is a break in elevation of 19 inches or more. 24 inches exceeds this threshold.", moduleRef:9, moduleName:"Ladders" },
  { q:"A 28-foot extension ladder is being used to access a rooftop. The base must be positioned at least how far from the wall?", options:["4 feet","5 feet","7 feet","8 feet"], a:2, explain:"4:1 rule: 28 ÷ 4 = 7 feet. The ladder base must be 7 feet from the wall to achieve the proper 75-degree working angle.", moduleRef:9, moduleName:"Ladders" },
  { q:"A Type III step ladder has a maximum load rating of:", options:["250 lbs","225 lbs","200 lbs","175 lbs"], a:2, explain:"Type III (light duty household) ladders have a duty rating of 200 lbs. This is the total load including the worker plus any tools, materials, or equipment.", moduleRef:9, moduleName:"Ladders" },
  { q:"A worker needs to reach 18 feet above the ground using an extension ladder. The ladder must extend to at least:", options:["18 feet","20 feet","21 feet","24 feet"], a:2, explain:"The ladder must reach the work height (18 feet) plus extend 3 feet above the landing. Therefore the ladder must reach at least 21 feet.", moduleRef:9, moduleName:"Ladders" },
  { q:"Which of the following is acceptable when using a stepladder?", options:["Using it in the folded position as a leaning ladder","Standing on the top two rungs","Spreading the legs fully and locking the spreaders","Straddling the top platform to reach higher"], a:2, explain:"Stepladders must be fully opened with spreader bars locked before use. Never use a stepladder folded, and never stand on the top two rungs — both are prohibited.", moduleRef:9, moduleName:"Ladders" },

  /* ── Module 10: Scaffolding ── */
  { q:"A worker on a two-point suspension (swing stage) scaffold must wear PFAS anchored to:", options:["The scaffold guardrail","The suspension ropes","A structural member of the building independent of the scaffold","The scaffold platform beams"], a:2, explain:"On suspended scaffolds, PFAS must be anchored to the building or structure — not the scaffold itself. If the scaffold fails, an anchor on the scaffold would fail with it.", moduleRef:10, moduleName:"Scaffolding" },
  { q:"Scaffold planks must extend beyond their end supports by:", options:["3 to 9 inches","4 to 12 inches","6 to 18 inches","12 to 24 inches"], a:2, explain:"OSHA requires scaffold planks to extend 6 to 18 inches beyond their end supports. Less than 6 inches risks the plank tipping; more than 18 inches creates a tip hazard if a worker steps on the overhang.", moduleRef:10, moduleName:"Scaffolding" },
  { q:"A mobile rolling scaffold is 15 feet tall. What is the MAXIMUM base width allowed?", options:["2.5 feet","3.75 feet","5 feet","7.5 feet"], a:1, explain:"4:1 height-to-base ratio: 15 ÷ 4 = 3.75 feet minimum base width. If the base is narrower than 3.75 feet, the scaffold is unstable. The base cannot be smaller than this minimum.", moduleRef:10, moduleName:"Scaffolding" },
  { q:"The competent person on a scaffold project must inspect the scaffold:", options:["Once per week","Before the start of each shift and after any condition that could affect integrity","Only when a new tier is added","Before any worker climbs above 10 feet"], a:1, explain:"The competent person must inspect the scaffold before each work shift and after any event that could affect integrity (rain, impact, overloading, ground movement).", moduleRef:10, moduleName:"Scaffolding" },
  { q:"Which of the following can a worker use to gain additional height on a scaffold platform?", options:["A step ladder","A milk crate or solid box","An inverted bucket","None of the above — platforms must not be supplemented"], a:3, explain:"Workers must not use ladders, boxes, crates, or other objects on scaffold platforms to gain additional height. The scaffold must be raised or reconstructed to reach higher elevations.", moduleRef:10, moduleName:"Scaffolding" },

  /* ── Module 11: Excavations ── */
  { q:"A freshly excavated trench is 6 feet deep in soil that was previously used as a landfill. How should this soil be classified?", options:["Type A — it is compacted fill","Type B — fill soil is medium-stability","Type C — previously disturbed soil cannot be Type A; landfill conditions indicate Type C","Type A if a pocket penetrometer reading supports it"], a:2, explain:"Previously disturbed soil cannot be classified as Type A, regardless of penetrometer readings. Landfill conditions also indicate mixed/contaminated soil. Classify as Type C and use appropriate protective systems.", moduleRef:11, moduleName:"Excavations" },
  { q:"Ladders must be provided in any excavation deeper than 4 feet, within how many feet of lateral travel?", options:["10 feet","15 feet","25 feet","35 feet"], a:2, explain:"Egress — ladders, stairs, or ramps — must be available in all excavations 4 feet or deeper, and workers must be within 25 feet of lateral travel from egress.", moduleRef:11, moduleName:"Excavations" },
  { q:"A shoring system in an excavation 22 feet deep must be designed by:", options:["A competent person","A qualified person","A registered professional engineer (PE)","Either a qualified person or competent person"], a:2, explain:"Protective systems for excavations deeper than 20 feet must be designed by a registered professional engineer. The standard OSHA Appendix tables only apply to depths of 20 feet or less.", moduleRef:11, moduleName:"Excavations" },
  { q:"The minimum distance that spoil piles must be kept from the edge of an excavation is:", options:["1 foot","2 feet","3 feet","4 feet"], a:1, explain:"Spoil piles (excavated soil) must be placed at least 2 feet from the edge of any excavation. This prevents additional loading (surcharge) on the trench wall that can cause cave-in.", moduleRef:11, moduleName:"Excavations" },
  { q:"A competent person must inspect an excavation:", options:["Before each work shift and after any hazard-increasing event","Only when a new protective system is installed","Once per week and after major storms","Whenever more than 5 workers are in the excavation"], a:0, explain:"The competent person must inspect excavations and adjacent areas before each shift, after rainstorms, after seismic activity, or after any other event that could increase hazards.", moduleRef:11, moduleName:"Excavations" },

  /* ── Module 12: Cranes & Rigging ── */
  { q:"A wire rope sling has 4 broken wires distributed throughout one rope lay. Should it be removed from service?", options:["No — 6 or more wires must be broken for removal","Yes — 4 broken wires meet the removal criteria of 6 per lay","No — broken wires only require removal if in one strand","Yes — any broken wire requires removal"], a:0, explain:"The removal threshold is 6 or more randomly distributed broken wires in one rope lay, or 3 or more in one strand. 4 distributed wires does not yet meet the 6-wire threshold, but the sling should be monitored closely.", moduleRef:12, moduleName:"Cranes" },
  { q:"A signal person is directing a crane operator. Mid-lift, a second supervisor on the ground gives a conflicting signal. The operator should:", options:["Obey the supervisor, who outranks the signal person","Follow the signal person's most recent instruction","Immediately stop all motion and not resume until confusion is resolved","Continue the original lift and sort out the confusion after"], a:2, explain:"Only one signal person may give signals to the operator at a time. When conflicting signals are given, the operator must stop until the situation is resolved. An emergency stop signal from anyone must always be obeyed.", moduleRef:12, moduleName:"Cranes" },
  { q:"A crane's load chart is not available in the cab. The operator should:", options:["Proceed using a conservative estimate of capacity","Use the manufacturer's posted maximum at the shortest boom length","Not operate the crane until the load chart is obtained","Call the manufacturer for verbal guidance"], a:2, explain:"The load chart must be in the cab and specific to the crane's current configuration. Operating without a load chart is a serious violation — the operator has no way to know safe load limits at any given radius.", moduleRef:12, moduleName:"Cranes" },
  { q:"A crane operator certification must be issued by:", options:["Any OSHA-accredited safety training provider","An accredited crane operator testing organization (e.g., NCCCO) or a qualifying employer program","The state in which the crane will be operated","The crane manufacturer"], a:1, explain:"Crane operators of cranes with rated capacity >2,000 lbs must be certified by an accredited crane testing organization (like NCCCO) or through a qualifying employer-based program meeting OSHA requirements.", moduleRef:12, moduleName:"Cranes" },
  { q:"The swing radius of a crane must be:", options:["Clearly visible from the operator's cab","Barricaded to prevent unauthorized entry","Painted yellow on the ground","At least 30 feet from any structure"], a:1, explain:"The area through which the crane superstructure and counterweight rotate must be barricaded to prevent workers from being struck if they unknowingly walk into the swing path.", moduleRef:12, moduleName:"Cranes" },

  /* ── Module 13: Tools ── */
  { q:"An abrasive grinding wheel emits a dull thud when tapped during the ring test. This means:", options:["The wheel has adequate density for the task","The wheel may be cracked and must not be used","The wheel needs to be balanced before use","The wheel is designed for wet grinding only"], a:1, explain:"The ring test checks for cracks. A clear ring = sound wheel. A dull thud = possible crack — the wheel must be removed from service. Using a cracked wheel can result in catastrophic disintegration at operating speed.", moduleRef:13, moduleName:"Tools" },
  { q:"The primary reason guards must never be removed from power tools is:", options:["OSHA will issue an automatic citation","Guards prevent contact with dangerous moving parts during normal operation","Guards prevent dust and debris from the work area","It voids the manufacturer's warranty"], a:1, explain:"Guards are engineering controls that physically prevent workers from contacting dangerous moving parts (blades, discs, rotating shafts). Removing them eliminates this protection and creates immediate danger.", moduleRef:13, moduleName:"Tools" },
  { q:"A pneumatic hose connection comes loose and the hose whips violently, striking a worker. This was caused by:", options:["Excessive air pressure above the tool's rating","Failure to use a safety wire, chain, or retainer on the hose connection","Using the wrong type of hose fittings","Operating the tool at too low a temperature"], a:1, explain:"Pneumatic hose connections must be secured with safety wires, chains, or equivalent at each connection point to prevent hose whip — a life-threatening hazard if a pressurized hose comes loose.", moduleRef:13, moduleName:"Tools" },
  { q:"A worker uses a screwdriver as a chisel to chip away at mortar. This is a violation because:", options:["Screwdrivers are only for electrical work","Using a tool for a purpose it was not designed for creates a hazard","Chipping mortar requires a licensed mason","The screwdriver may create sparks near flammable materials"], a:1, explain:"OSHA requires using the right tool for the job. Screwdrivers are not designed to withstand impact — the handle can crack or the shaft can slip, causing injuries. Use a cold chisel and hammer instead.", moduleRef:13, moduleName:"Tools" },
  { q:"Double-insulated power tools are identified by:", options:["A red label on the tool body","A double-square symbol on the tool or packaging","The absence of a ground prong on the plug","A '2X' rating on the motor specification plate"], a:1, explain:"Double-insulated tools are marked with a double-square symbol (a square inside a square). They provide two independent layers of insulation and do not require a third grounding prong.", moduleRef:13, moduleName:"Tools" },

  /* ── Module 14: Materials Handling ── */
  { q:"When transporting compressed gas cylinders by vehicle, they must be:", options:["Laid horizontally to lower the center of gravity","Secured in an upright position with the valve caps on","Stored with regulators attached to prevent valve damage","Kept at least 5 feet apart if different gases"], a:1, explain:"Cylinders must be transported upright (except acetylene, which must always be upright), secured against tipping, and with protective valve caps in place when regulators are not attached.", moduleRef:14, moduleName:"Materials Handling" },
  { q:"A 50-gallon drum of flammable solvent is needed for a day's work. The maximum amount that may be in the work area is:", options:["50 gallons — the full drum","25 gallons — one day's supply in approved containers","10 gallons in any container","5 gallons — one safety can maximum"], a:1, explain:"No more than 25 gallons (one day's supply) of flammable liquid may be in the work area at any time. Larger quantities must be kept in approved storage rooms or cabinets.", moduleRef:14, moduleName:"Materials Handling" },
  { q:"The NIOSH Recommended Weight Limit (RWL) for manual lifting under ideal conditions is:", options:["35 lbs","51 lbs","65 lbs","75 lbs"], a:1, explain:"The NIOSH RWL under ideal lifting conditions (load at waist height, close to body, good grip, no twist, infrequent) is 51 lbs. This decreases with less-than-ideal conditions.", moduleRef:14, moduleName:"Materials Handling" },
  { q:"A forklift operator must be re-evaluated on their operating performance at least every:", options:["1 year","2 years","3 years","5 years"], a:2, explain:"OSHA requires forklift operators to be evaluated on their operating performance at least every 3 years. Retraining and re-evaluation are required after accidents, near-misses, unsafe operation, or assignment to a new truck type.", moduleRef:14, moduleName:"Materials Handling" },
  { q:"When stacking materials in storage, aisles must be at least how wide?", options:["2 feet","3 feet","4 feet","5 feet"], a:1, explain:"OSHA requires that aisles and passageways be kept at least 3 feet wide and clear of materials at all times. This ensures safe movement of workers and material handling equipment.", moduleRef:14, moduleName:"Materials Handling" },

  /* ── Module 15: Concrete & Masonry ── */
  { q:"A masonry wall is 12 feet tall and is being constructed. The required Limited Access Zone on the unscaffolded side extends:", options:["12 feet from the base of the wall","16 feet from the base of the wall","4 feet from the wall face","12 feet wide, running half the wall's length"], a:1, explain:"The LAZ width equals the wall height + 4 feet. For a 12-foot wall: 12 + 4 = 16 feet. It runs the entire length of the wall on the unscaffolded face.", moduleRef:15, moduleName:"Concrete" },
  { q:"Wet concrete has a pH of approximately 12.5. This means skin contact can cause:", options:["Acid burns requiring immediate neutralization with vinegar","Alkali chemical burns that may not be painful initially","Mild irritation that resolves without treatment","No harm — concrete is non-reactive with skin"], a:1, explain:"At pH 12.5, wet concrete is highly alkaline. Alkali burns destroy skin tissue and may be initially painless — making them deceptively dangerous. Workers must wash off cement immediately and wear protective gloves.", moduleRef:15, moduleName:"Concrete" },
  { q:"Who must design formwork for concrete construction?", options:["Any experienced carpenter","A competent person at the site","A qualified person","Any licensed contractor"], a:2, explain:"Formwork must be designed by or under the supervision of a qualified person — someone with recognized credentials or experience sufficient to solve problems relating to the subject matter.", moduleRef:15, moduleName:"Concrete" },
  { q:"Lift-slab construction requires jacks to be:", options:["Operated manually by ironworkers inside the lift zone","Synchronized and capable of stopping the slab in any position","Certified by a third-party inspector before each lift","Rated for 4x the slab's calculated weight"], a:1, explain:"In lift-slab operations, jacks must be synchronized so all points of the slab rise at the same rate, and must be capable of stopping and holding the slab at any position in case of a malfunction.", moduleRef:15, moduleName:"Concrete" },
  { q:"The primary silica dust control when cutting concrete masonry units with a saw is:", options:["Respirators for all workers in the area","Water suppression or local exhaust ventilation (LEV) at the blade","Reducing cutting speed","Scheduling dusty cuts during low-wind conditions"], a:1, explain:"Engineering controls — wet cutting (water at the blade) or LEV/HEPA vacuum collection at the source — are the primary controls for silica dust from masonry saws. Respirators are supplemental, not primary.", moduleRef:15, moduleName:"Concrete" },

  /* ── Module 16: Steel Erection ── */
  { q:"Before a crane can release a steel column that was just set, the column must have:", options:["Been visually plumbed by the ironworker crew","At least 4 anchor bolts installed and tightened","Both flange connections bolted up","Been inspected by the structural engineer"], a:1, explain:"A minimum of 4 anchor bolts per column must be installed and tightened before the crane releases the column. This is a specific Subpart R requirement to prevent column tip-over.", moduleRef:16, moduleName:"Steel Erection" },
  { q:"What is the maximum advance of a Controlled Decking Zone (CDZ) ahead of the leading edge?", options:["15 feet","20 feet","30 feet","45 feet"], a:2, explain:"A CDZ may advance no more than 30 feet ahead of the leading edge. Beyond that, connectors must use conventional fall protection (PFAS or other systems).", moduleRef:16, moduleName:"Steel Erection" },
  { q:"The maximum number of structural members that may be rigged in a single multiple-lift is:", options:["3","5","8","10"], a:1, explain:"Multiple-lift (Christmas tree) rigging is limited to 5 structural members per lift, rigged from the top member down, and must be under the direction of a qualified rigger with a pre-lift meeting held.", moduleRef:16, moduleName:"Steel Erection" },
  { q:"Tag lines in steel erection are required to:", options:["Attach the worker's safety harness to the structure","Control suspended structural members during crane picks","Mark the load weight on the crane's load indicator","Connect the signal person's radio to the crane cab"], a:1, explain:"Tag lines are required during steel erection to control the swinging and rotation of suspended structural members. Workers must never stand in the direct path of a swinging load.", moduleRef:16, moduleName:"Steel Erection" },
  { q:"The Site-Specific Erection Plan (SSEP) for steel erection must be developed:", options:["After the first week of erection, based on field conditions","Before steel erection begins","Only for projects with cranes over 50-ton capacity","Only when workers will be more than 30 feet above grade"], a:1, explain:"The SSEP must be in place before any steel erection begins. It addresses the sequence of erection, fall protection, crane locations, rigging, communication, and other site-specific safety factors.", moduleRef:16, moduleName:"Steel Erection" },

  /* ── Module 17: Fire Protection ── */
  { q:"A fire breaks out in a bucket of diesel fuel stored on the construction site. Which extinguisher agent should be used?", options:["Water — diesel is easily cooled","Class A dry chemical","Class ABC dry chemical or CO₂","Class D dry powder"], a:2, explain:"Diesel fuel is a flammable liquid — a Class B fire. An ABC dry chemical or CO₂ extinguisher is appropriate. Water must NOT be used on flammable liquid fires — it spreads the burning liquid.", moduleRef:17, moduleName:"Fire Protection" },
  { q:"Materials stored in a building with an active sprinkler system must maintain clearance below sprinkler heads of:", options:["6 inches","12 inches","18 inches","24 inches"], a:2, explain:"At least 18 inches of clearance must be maintained below all sprinkler heads. Blocking sprinklers prevents them from effectively dispersing water over the fire area.", moduleRef:17, moduleName:"Fire Protection" },
  { q:"A fire watch is NOT required after welding/cutting operations when:", options:["The work area has been thoroughly soaked with water","A CO₂ extinguisher is on standby","No combustibles are within 35 feet AND all exposed surfaces are noncombustible","The welding is performed outdoors"], a:2, explain:"OSHA allows exemption from fire watch when there are no combustibles within 35 feet AND all surfaces are noncombustible and cannot conduct heat to ignite combustibles on the other side.", moduleRef:17, moduleName:"Fire Protection" },
  { q:"The 'S' in the PASS fire extinguisher technique stands for:", options:["Spray the agent","Stop and assess","Squeeze the trigger","Sweep side to side"], a:3, explain:"PASS: Pull the pin → Aim at the base of the fire → Squeeze the handle → Sweep side to side across the base of the fire. Both the second 'S' and the technique remind you to sweep at the base.", moduleRef:17, moduleName:"Fire Protection" },
  { q:"Fire extinguishers must be inspected:", options:["Only when placed in service and after any use","Annually by a licensed fire protection company only","Monthly (visual inspection) and annually (service/maintenance)","Quarterly and whenever they are moved"], a:2, explain:"OSHA requires fire extinguishers to be visually inspected monthly and serviced/maintained annually by a trained person. Tags on the extinguisher document inspection history.", moduleRef:17, moduleName:"Fire Protection" },

  /* ── Module 18: Welding & Cutting ── */
  { q:"Acetylene must never be used at a pressure above:", options:["5 psi","15 psi","30 psi","50 psi"], a:1, explain:"Acetylene is chemically unstable at pressures above 15 psi and can decompose explosively without oxygen present. Never use acetylene at pressures exceeding 15 psi.", moduleRef:18, moduleName:"Welding" },
  { q:"When welding or cutting in a confined space, compressed gas cylinders must be:", options:["Secured inside the space near the work area for quick access","Removed from the space when welding is not actively occurring","Fitted with check valves before entering the confined space","Stored horizontally inside the space to reduce the risk of falling"], a:1, explain:"Cylinders must be removed from confined spaces when welding/cutting stops. A leaking cylinder inside a confined space creates a flammable/explosive atmosphere or displaces oxygen.", moduleRef:18, moduleName:"Welding" },
  { q:"The minimum general ventilation for arc welding is approximately:", options:["2,000 cubic feet per minute OR 10,000 cubic feet of space per welder","5,000 cubic feet per minute","1,000 cubic feet of space per welder","15 air changes per hour"], a:0, explain:"Per OSHA's welding standards, general ventilation requires at least 2,000 cfm of airflow per welder, or at least 10,000 cubic feet of space per welder with natural air movement. Less than this requires mechanical ventilation.", moduleRef:18, moduleName:"Welding" },
  { q:"Welding on cadmium-coated metal requires enhanced controls because cadmium fumes can cause:", options:["Chemical eye burns","Acute kidney damage and long-term cancer risk","Immediate cardiac arrest at any exposure level","Silicosis after years of exposure"], a:1, explain:"Cadmium is a highly toxic heavy metal. Even brief exposures to cadmium fumes can cause acute kidney damage, chemical pneumonia, and pulmonary edema. Long-term exposure is linked to cancer.", moduleRef:18, moduleName:"Welding" },
  { q:"Eye protection for arc welding (SMAW/GMAW) must have a minimum shade of:", options:["#5","#7","#10","#12"], a:2, explain:"The minimum recommended shade for standard arc welding (SMAW, GMAW) is shade #10. Higher amperages require shade #12 or #14. Using too light a shade causes arc eye — UV keratitis.", moduleRef:18, moduleName:"Welding" },

  /* ── Module 19: Motor Vehicles ── */
  { q:"On a construction site, a vehicle operator's view to the rear is fully obstructed by the load. The operator must:", options:["Proceed slowly using mirrors","Use a backup alarm only","Use a backup alarm AND a designated spotter","Stop work until a backup camera is installed"], a:2, explain:"When the operator cannot see the work area behind the vehicle, BOTH a backup alarm AND a spotter (or an equivalent means of alerting workers) are required. Neither alone is sufficient.", moduleRef:19, moduleName:"Motor Vehicles" },
  { q:"ROPS (Rollover Protective Structures) protect operators most effectively when:", options:["The operator is wearing a seatbelt and remains in the cab","The cab has additional ballast weight added","The machine is traveling at low speed","The ROPS has been welded to additional supports"], a:0, explain:"ROPS works as a protective cage only when the operator remains in the seat — which requires wearing a seatbelt. Without a seatbelt, the operator is ejected and may be crushed by the ROPS.", moduleRef:19, moduleName:"Motor Vehicles" },
  { q:"A worker hitches a ride on the bucket of a loader because no other transportation is available. This is:", options:["Allowed in an emergency","Prohibited — riders only permitted where seats are provided","Allowed at speeds below 5 mph","Allowed if the bucket is lowered to within 1 foot of the ground"], a:1, explain:"Riding on equipment is only permitted when a seat designed for a passenger is provided. Riding in/on buckets, forks, fenders, or any non-designated area is strictly prohibited.", moduleRef:19, moduleName:"Motor Vehicles" },
  { q:"Construction equipment operating near overhead power lines rated at 69kV must maintain a minimum clearance of:", options:["10 feet","15 feet","20 feet","25 feet"], a:1, explain:"For voltages between 50.1kV and 200kV (which includes 69kV), a minimum clearance of 15 feet is required from overhead power lines. The 10-foot rule only applies to up to 50kV.", moduleRef:19, moduleName:"Motor Vehicles" },
  { q:"Pre-operation inspections for construction vehicles are required:", options:["Weekly, by a certified mechanic","At the beginning of each shift, by the operator or a designated person","Monthly, with documentation filed","After every 8 hours of operation"], a:1, explain:"29 CFR 1926.601 requires that motor vehicles be inspected at the beginning of each shift. Defects must be corrected before the vehicle is placed back in service.", moduleRef:19, moduleName:"Motor Vehicles" },

  /* ── Module 20: Confined Spaces ── */
  { q:"An oxygen reading of 24% inside a permit-required confined space indicates:", options:["A safe, oxygen-rich environment — entry is permitted","Oxygen enrichment — a hazardous atmosphere; increased fire/explosion risk","Oxygen deficiency — entry is prohibited","Normal conditions — outdoor air is 21% O₂"], a:1, explain:"Oxygen above 23.5% is oxygen-enriched — a hazardous atmosphere. Enriched oxygen dramatically increases the flammability of materials and the risk of fire and explosion.", moduleRef:20, moduleName:"Confined Spaces" },
  { q:"A confined space entry permit is valid for:", options:["The duration of the project","The authorized duration specified on the permit — canceled when work is done or conditions change","24 hours from issuance, then it must be renewed","8 hours — one standard work shift"], a:1, explain:"Entry permits must specify the date and authorized duration of the entry. They must be canceled when work is complete or when a change in conditions makes the permit conditions invalid.", moduleRef:20, moduleName:"Confined Spaces" },
  { q:"The attendant for a confined space entry becomes aware that the entrant is in distress. The FIRST action the attendant should take is:", options:["Enter the space with a respirator to assess the situation","Order the entrant to self-rescue; if unable, call for rescue/911 and attempt non-entry rescue","Wait 5 minutes to see if the entrant recovers","Call the supervisor before taking any action"], a:1, explain:"The attendant must order evacuation, summon emergency rescue (call 911), and attempt non-entry rescue (retrieval system). The attendant must NEVER enter the space — this turns one victim into two.", moduleRef:20, moduleName:"Confined Spaces" },
  { q:"Which of the following is NOT a characteristic that makes a confined space permit-required?", options:["It contains a hazardous atmosphere","It has limited means of entry or exit","It contains a material that could engulf workers","It has an internal configuration that could trap or asphyxiate workers"], a:1, explain:"Limited means of entry/exit is a characteristic of all confined spaces, but alone does NOT make a space permit-required. A space requires a permit when it has a hazardous atmosphere, engulfment hazard, entrapment geometry, or other recognized serious hazard.", moduleRef:20, moduleName:"Confined Spaces" },
  { q:"Before any worker enters a permit-required confined space, the entry supervisor must:", options:["Verify that rescue services are standing by inside the space","Verify that all permit conditions are met and authorize the entry","Conduct a 30-minute ventilation cycle without testing","Post a warning sign and document the entry time"], a:1, explain:"The entry supervisor must verify that all conditions on the permit have been met — including atmospheric testing, ventilation, PPE, rescue equipment, and attendant is in place — before authorizing entry.", moduleRef:20, moduleName:"Confined Spaces" }
];
