/* OSHA 30 Construction — Flashcard Key Terms (~10 per module, 200 total) */
const FLASHCARDS = [
  /* ── Module 1: Introduction to OSHA ── */
  { id:"m1_1", term:"OSH Act", definition:"The Occupational Safety and Health Act of 1970, signed December 29, 1970. Created OSHA and NIOSH to protect workers from job-related hazards.", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_2", term:"29 CFR Part 1926", definition:"The Code of Federal Regulations section covering Safety and Health Regulations for Construction. All OSHA construction standards are found here.", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_3", term:"General Duty Clause", definition:"Section 5(a)(1) of the OSH Act — requires employers to provide a workplace free from recognized hazards even when no specific OSHA standard applies.", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_4", term:"Willful Violation", definition:"An OSHA violation committed intentionally or with knowledge that a hazard exists. Maximum penalty: $156,259 per violation.", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_5", term:"Serious Violation", definition:"An OSHA violation where there is substantial probability of death or serious physical harm. Maximum penalty: $15,625 per day.", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_6", term:"Right to Refuse", definition:"A worker's legal right to refuse work they reasonably believe poses imminent danger of death or serious injury, when there is no time to eliminate the hazard through normal channels.", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_7", term:"CSHO", definition:"Compliance Safety and Health Officer — the OSHA inspector who conducts workplace inspections and may issue citations.", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_8", term:"State Plan", definition:"A state-run occupational safety program approved by OSHA. Must be at least as effective as federal OSHA. Currently 22 states and territories operate State Plans.", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_9", term:"NIOSH", definition:"National Institute for Occupational Safety and Health — part of the CDC. Conducts safety research and recommends new standards. Does NOT enforce standards (OSHA does).", moduleId:1, moduleName:"Intro to OSHA" },
  { id:"m1_10", term:"Repeat Violation", definition:"A violation of the same or substantially similar standard within 5 years of a previous citation. Same maximum penalty as willful: $156,259 per violation.", moduleId:1, moduleName:"Intro to OSHA" },

  /* ── Module 2: Managing Safety & Health ── */
  { id:"m2_1", term:"Hierarchy of Controls", definition:"Ranked framework for hazard control: Elimination → Substitution → Engineering Controls → Administrative Controls → PPE. Higher levels are more effective and preferred.", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_2", term:"Engineering Controls", definition:"Physical changes to the workplace that reduce or eliminate hazards at the source — guards, ventilation, noise enclosures, barriers. More effective than PPE.", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_3", term:"Job Hazard Analysis (JHA)", definition:"A proactive process that breaks a job into steps, identifies hazards in each step, and recommends controls before work begins. Also called Job Safety Analysis (JSA).", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_4", term:"Near-Miss", definition:"An unplanned event that did not result in injury, illness, or damage but had the potential to do so. Must be reported and investigated to prevent future incidents.", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_5", term:"OSHA 300 Log", definition:"The OSHA form used to record work-related injuries and illnesses throughout the calendar year. Must be maintained by employers with 11+ employees in most industries.", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_6", term:"OSHA 300A", definition:"The annual summary of the OSHA 300 Log. Must be posted in a visible workplace location from February 1 through April 30 of the following year. Must be certified by a company executive.", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_7", term:"Recordable Incident", definition:"A work-related injury or illness resulting in: death, days away from work, restricted duty, medical treatment beyond first aid, loss of consciousness, or a significant diagnosis.", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_8", term:"Toolbox Talk", definition:"A short, informal safety meeting held at the start of a work shift to discuss daily hazards, safety topics, and reinforce safe work practices.", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_9", term:"Root Cause Analysis", definition:"An investigation method that asks 'why did it happen?' rather than just 'what happened?' — identifying the underlying causes of an incident to prevent recurrence.", moduleId:2, moduleName:"Safety Programs" },
  { id:"m2_10", term:"OSHA 301", definition:"The Incident Report form providing detailed information about each recordable injury or illness. Must be completed within 7 days of the employer learning of the incident.", moduleId:2, moduleName:"Safety Programs" },

  /* ── Module 3: Fall Hazards ── */
  { id:"m3_1", term:"Personal Fall Arrest System (PFAS)", definition:"A fall protection system consisting of a full-body harness, connecting means (lanyard/SRL), and anchorage point. Must limit free fall to 6 ft and arrest force to 1,800 lbs.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_2", term:"Anchorage Point", definition:"The secure point to which a PFAS is attached. Must be capable of supporting at least 5,000 lbs per worker attached, or designed by a qualified person to maintain a 2:1 safety factor.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_3", term:"Guardrail System", definition:"A fall protection system consisting of a top rail (42\" ±3\"), midrail (~21\"), and toeboard. Must withstand 200 lbs of force in any outward or downward direction.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_4", term:"Leading Edge", definition:"The unprotected edge of a floor, roof, or formwork that changes location as construction progresses. Workers at leading edges need fall protection or a written fall protection plan.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_5", term:"Deceleration Distance", definition:"The distance a PFAS allows a worker to travel after the lanyard/SRL begins to engage before coming to a complete stop. OSHA limit: 3.5 feet maximum.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_6", term:"Safety Net System", definition:"A fall protection method using nets installed below the work area. Must be installed within 30 feet below the working surface and extend beyond the outermost edge.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_7", term:"Self-Retracting Lifeline (SRL)", definition:"A connecting device that automatically extends and retracts as the worker moves. Activates quickly to arrest a fall with minimal free fall distance.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_8", term:"Fall Protection Trigger Height", definition:"The height at which fall protection is required in construction: 6 feet above a lower level (29 CFR 1926.502). General industry trigger is 4 feet.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_9", term:"Toeboard", definition:"A barrier at least 3.5 inches high installed at the edge of elevated surfaces to prevent tools and materials from sliding or rolling off onto workers below.", moduleId:3, moduleName:"Fall Hazards" },
  { id:"m3_10", term:"Free Fall Distance", definition:"The vertical distance a worker falls before a PFAS begins to apply braking force. OSHA limits free fall to a maximum of 6 feet when using a PFAS.", moduleId:3, moduleName:"Fall Hazards" },

  /* ── Module 4: Electrical Hazards ── */
  { id:"m4_1", term:"GFCI", definition:"Ground Fault Circuit Interrupter — detects leakage current of 4–6 milliamps and trips the circuit in 1/40th of a second. Required for all 120V, 15/20A construction site receptacles.", moduleId:4, moduleName:"Electrical" },
  { id:"m4_2", term:"AEGCP", definition:"Assured Equipment Grounding Conductor Program — an OSHA-approved alternative to GFCI that requires a written program, visual inspections before each use, and scheduled electrical testing.", moduleId:4, moduleName:"Electrical" },
  { id:"m4_3", term:"Arc Flash", definition:"An intense release of thermal energy (heat and light) from an electrical arc. Temperatures can reach 35,000°F, causing severe burns and other injuries.", moduleId:4, moduleName:"Electrical" },
  { id:"m4_4", term:"Lockout/Tagout (LOTO)", definition:"A safety procedure (29 CFR 1926.417) that isolates hazardous energy sources and renders equipment inoperable before maintenance. Only the employee who applied the lock may remove it.", moduleId:4, moduleName:"Electrical" },
  { id:"m4_5", term:"Double Insulation", definition:"A tool safety design using two independent layers of insulation instead of a ground wire. Identified by the double-square symbol (□□). Does not require a 3-prong grounded plug.", moduleId:4, moduleName:"Electrical" },
  { id:"m4_6", term:"Ground Fault", definition:"Unintended electrical current flowing from an energized conductor to ground — often through a person's body. GFCIs are designed to detect and interrupt ground faults.", moduleId:4, moduleName:"Electrical" },
  { id:"m4_7", term:"Overhead Power Line Clearance", definition:"Minimum safe distance from energized overhead power lines. For voltages up to 50kV: 10 feet minimum. Higher voltages require greater clearances.", moduleId:4, moduleName:"Electrical" },
  { id:"m4_8", term:"Ventricular Fibrillation", definition:"A life-threatening heart arrhythmia caused by electrical current passing through the chest. Can be triggered by as little as 50–100 milliamps (0.05–0.1 amps).", moduleId:4, moduleName:"Electrical" },
  { id:"m4_9", term:"Stored Energy", definition:"Energy remaining in a machine or system after it has been shut off — capacitor charge, spring tension, hydraulic pressure, gravity. Must be released or restrained during LOTO.", moduleId:4, moduleName:"Electrical" },

  /* ── Module 5: Struck-By Hazards ── */
  { id:"m5_1", term:"Line of Fire", definition:"The path along which a tool, equipment, or material could travel if released, propelled, or dropped. Workers must never position themselves in the line of fire.", moduleId:5, moduleName:"Struck-By" },
  { id:"m5_2", term:"Flying Object Hazard", definition:"A struck-by hazard involving a projectile (nail, debris, chip) propelled by a tool or equipment. Requires eye/face protection and awareness of tool direction.", moduleId:5, moduleName:"Struck-By" },
  { id:"m5_3", term:"Tag Line", definition:"A rope or cable attached to a crane-suspended load to control its swinging and rotation. Required during crane picks to keep the load under control.", moduleId:5, moduleName:"Struck-By" },
  { id:"m5_4", term:"High-Visibility Apparel", definition:"ANSI/ISEA 107-rated reflective garments. Class 1 = low risk; Class 2 = minimum for roadway work zones; Class 3 = high traffic or nighttime use.", moduleId:5, moduleName:"Struck-By" },
  { id:"m5_5", term:"Spotter", definition:"A designated worker who guides equipment operators when their view is obstructed. Must maintain direct visual contact with the operator and use prearranged signals.", moduleId:5, moduleName:"Struck-By" },
  { id:"m5_6", term:"Backup Alarm", definition:"An audible warning device required on vehicles/equipment when the operator cannot see behind them. Must be audible above ambient noise levels.", moduleId:5, moduleName:"Struck-By" },
  { id:"m5_7", term:"Falling Object Protection", definition:"Methods to prevent tools/materials from falling onto workers below elevated work — toeboards, canopies, debris nets, barricades, and tool tethers.", moduleId:5, moduleName:"Struck-By" },
  { id:"m5_8", term:"Swing Radius", definition:"The area swept by a crane's counterweight and superstructure during rotation. Must be barricaded to prevent workers from being struck during crane operation.", moduleId:5, moduleName:"Struck-By" },

  /* ── Module 6: Caught-In/Between ── */
  { id:"m6_1", term:"Pinch Point", definition:"A location where two objects come together, with at least one moving, creating a risk of body parts being caught between them. Common with gears, belt drives, and pulleys.", moduleId:6, moduleName:"Caught-In" },
  { id:"m6_2", term:"Wrap Point", definition:"An exposed rotating shaft or component that can catch and wrap clothing, hair, or jewelry — pulling the worker into the machine within fractions of a second.", moduleId:6, moduleName:"Caught-In" },
  { id:"m6_3", term:"Point of Operation", definition:"The area of a machine where work is performed on material — where the highest risk of contact with moving parts exists. Must be guarded.", moduleId:6, moduleName:"Caught-In" },
  { id:"m6_4", term:"Interlocked Guard", definition:"A machine guard connected to the power supply so that the machine automatically stops when the guard is opened or removed.", moduleId:6, moduleName:"Caught-In" },
  { id:"m6_5", term:"Nip Point", definition:"The point where two rotating parts contact each other, or where a rotating part contacts a stationary surface — creating a risk of drawing in body parts.", moduleId:6, moduleName:"Caught-In" },
  { id:"m6_6", term:"Surcharge Load", definition:"Additional weight placed on the edge of an excavation (spoil piles, equipment, vehicles) that increases the risk of wall collapse. Spoil must be kept at least 2 feet from the edge.", moduleId:6, moduleName:"Caught-In" },
  { id:"m6_7", term:"Shear Point", definition:"A caught-in/between hazard where the edge of a moving part passes closely against a stationary part or another moving part — like scissors.", moduleId:6, moduleName:"Caught-In" },

  /* ── Module 7: PPE ── */
  { id:"m7_1", term:"Class E Hard Hat", definition:"Electrical class hard hat rated to withstand 20,000 volts. Required when working near high-voltage electrical equipment.", moduleId:7, moduleName:"PPE" },
  { id:"m7_2", term:"Class G Hard Hat", definition:"General class hard hat rated to withstand 2,200 volts. Suitable for most construction work unless higher voltage exposure exists.", moduleId:7, moduleName:"PPE" },
  { id:"m7_3", term:"Type II Hard Hat", definition:"Hard hat providing impact protection on both the top AND the sides (lateral impact). More protective than Type I, which only protects the top.", moduleId:7, moduleName:"PPE" },
  { id:"m7_4", term:"NRR", definition:"Noise Reduction Rating — the decibel reduction provided by hearing protection under ideal lab conditions. Real-world effectiveness is lower; OSHA's method: (NRR – 7) ÷ 2.", moduleId:7, moduleName:"PPE" },
  { id:"m7_5", term:"Action Level (Noise)", definition:"The noise exposure level at which an employer must implement a hearing conservation program: 85 dB as an 8-hour TWA. Below this, no mandatory program required.", moduleId:7, moduleName:"PPE" },
  { id:"m7_6", term:"PEL (Noise)", definition:"Permissible Exposure Limit for noise: 90 dB as an 8-hour TWA. Engineering or administrative controls must be implemented when exposures reach the PEL.", moduleId:7, moduleName:"PPE" },
  { id:"m7_7", term:"ANSI Z87.1", definition:"The American standard for eye and face protective devices (safety glasses, goggles, face shields). All eye/face PPE in construction must meet this standard.", moduleId:7, moduleName:"PPE" },
  { id:"m7_8", term:"Fit Test", definition:"A qualitative or quantitative test to confirm a tight-fitting respirator creates an adequate face seal for a specific worker. Required before first use and annually thereafter.", moduleId:7, moduleName:"PPE" },
  { id:"m7_9", term:"SCBA", definition:"Self-Contained Breathing Apparatus — provides the highest level of respiratory protection; supplies its own breathable air. Required in IDLH atmospheres.", moduleId:7, moduleName:"PPE" },
  { id:"m7_10", term:"ASTM F2413", definition:"The current standard for protective footwear (safety-toe boots) used in construction. Replaces the older ANSI Z41 standard.", moduleId:7, moduleName:"PPE" },

  /* ── Module 8: Health Hazards & HazCom ── */
  { id:"m8_1", term:"GHS", definition:"Globally Harmonized System of Classification and Labelling of Chemicals. Standardizes hazard communication worldwide using 9 pictograms, signal words, and SDS format.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_2", term:"SDS", definition:"Safety Data Sheet — 16-section standardized document providing detailed chemical hazard and safe handling information. Replaced the MSDS under GHS HazCom 2012.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_3", term:"Signal Word", definition:"A GHS label element indicating hazard severity. Only two options: DANGER (more severe) and WARNING (less severe). These are the only two GHS signal words.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_4", term:"IDLH", definition:"Immediately Dangerous to Life or Health — the concentration of a substance that poses an immediate threat. SCBA or supplied-air respirators required at or above IDLH levels.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_5", term:"Silicosis", definition:"An irreversible, progressive lung disease caused by inhaling crystalline silica dust. Common in workers who cut, grind, drill, or jackhammer concrete, masonry, or rock.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_6", term:"PEL (Silica)", definition:"Permissible Exposure Limit for respirable crystalline silica: 50 µg/m³ as an 8-hour TWA. Action level (triggers medical surveillance): 25 µg/m³.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_7", term:"PEL (Asbestos)", definition:"Permissible Exposure Limit for asbestos: 0.1 fibers per cubic centimeter (f/cc) as an 8-hour TWA. STEL (30-min limit): 1.0 f/cc.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_8", term:"Routes of Entry", definition:"The four ways chemicals can enter the body: Inhalation (most common for airborne hazards), Ingestion, Skin Absorption, and Injection.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_9", term:"TWA", definition:"Time-Weighted Average — the average airborne concentration of a substance over an 8-hour workday. Used to compare exposures to OSHA PELs and action levels.", moduleId:8, moduleName:"Health Hazards" },
  { id:"m8_10", term:"Mesothelioma", definition:"A rare, aggressive cancer of the lining of the lungs or abdomen caused almost exclusively by asbestos exposure. Often diagnosed 20–50 years after exposure.", moduleId:8, moduleName:"Health Hazards" },

  /* ── Module 9: Stairways & Ladders ── */
  { id:"m9_1", term:"4:1 Ladder Rule", definition:"The correct angle for extension ladders: for every 4 feet of ladder height, position the base 1 foot away from the wall (approximately 75 degrees from horizontal).", moduleId:9, moduleName:"Ladders" },
  { id:"m9_2", term:"Three-Point Contact", definition:"The safe climbing technique requiring two hands and one foot, or two feet and one hand, on the ladder at all times when ascending or descending.", moduleId:9, moduleName:"Ladders" },
  { id:"m9_3", term:"Type IA Ladder", definition:"Extra heavy-duty ladder with a maximum load rating of 300 lbs. Suitable for industrial use where the worker plus tools may approach this limit.", moduleId:9, moduleName:"Ladders" },
  { id:"m9_4", term:"Duty Rating", definition:"The maximum load capacity of a ladder, including the worker's body weight plus all tools, materials, and equipment being carried. Must never be exceeded.", moduleId:9, moduleName:"Ladders" },
  { id:"m9_5", term:"Extension Ladder Overlap", definition:"The required overlap between the fly (upper) and base sections of an extension ladder: varies by length. Provides stability at the joint.", moduleId:9, moduleName:"Ladders" },
  { id:"m9_6", term:"3-Foot Rule (Ladders)", definition:"Extension ladders used for access to upper levels must extend at least 3 feet above the landing surface to provide a handhold when stepping on or off.", moduleId:9, moduleName:"Ladders" },
  { id:"m9_7", term:"19-Inch Rule", definition:"OSHA requires a stairway or ladder at every elevation change of 19 inches or more on a construction site (29 CFR 1926.1051).", moduleId:9, moduleName:"Ladders" },
  { id:"m9_8", term:"Job-Made Ladder", definition:"A ladder constructed on-site rather than commercially manufactured. Must be designed by a qualified person and comply with OSHA's strength and spacing requirements.", moduleId:9, moduleName:"Ladders" },

  /* ── Module 10: Scaffolding ── */
  { id:"m10_1", term:"Competent Person (Scaffold)", definition:"The individual responsible for overseeing scaffold erection, alteration, dismantling, and daily inspection. Must have the knowledge to identify hazards and the authority to correct them.", moduleId:10, moduleName:"Scaffolding" },
  { id:"m10_2", term:"Qualified Person (Scaffold)", definition:"A person with recognized credentials or experience sufficient to design a scaffold system. The qualified person designs the scaffold; the competent person oversees its use.", moduleId:10, moduleName:"Scaffolding" },
  { id:"m10_3", term:"Supported Scaffold", definition:"A scaffold platform supported from below by rigid legs, frames, poles, or similar supports. The most common type on construction sites. Safety factor: 4:1.", moduleId:10, moduleName:"Scaffolding" },
  { id:"m10_4", term:"Suspended Scaffold", definition:"A scaffold hung from above by ropes, cables, or other non-rigid means (swing stages, boatswain's chairs). Safety factor: 6:1. Workers must wear PFAS.", moduleId:10, moduleName:"Scaffolding" },
  { id:"m10_5", term:"Mudsill", definition:"A wide base plate or structural member placed under scaffold base plates on soft or unstable ground to distribute the load and prevent sinking or shifting.", moduleId:10, moduleName:"Scaffolding" },
  { id:"m10_6", term:"Safety Factor (Scaffold)", definition:"The ratio of a scaffold's capacity to the actual load applied. Supported scaffolds: 4:1 minimum. Suspended scaffolds: 6:1 minimum.", moduleId:10, moduleName:"Scaffolding" },
  { id:"m10_7", term:"Scaffold Fall Protection Trigger", definition:"Fall protection (guardrails or PFAS) is required when scaffold platforms are 10 feet or more above a lower level — different from the 6-foot trigger for other construction work.", moduleId:10, moduleName:"Scaffolding" },
  { id:"m10_8", term:"Planking Overhang Rule", definition:"Scaffold planks must extend 6 to 18 inches beyond their end supports. Less risks tipping; more than 18 inches creates a trip/tip hazard.", moduleId:10, moduleName:"Scaffolding" },

  /* ── Module 11: Excavations & Trenching ── */
  { id:"m11_1", term:"Type A Soil", definition:"The most stable soil classification (cohesive — clay, hardpan). No fissures, vibration, water, or previous disturbance. Maximum slope: ¾:1 (53°).", moduleId:11, moduleName:"Excavations" },
  { id:"m11_2", term:"Type C Soil", definition:"The least stable soil classification (granular, wet, submerged, previously disturbed, or layered). Maximum slope: 1½:1 (34°). Benching NOT permitted.", moduleId:11, moduleName:"Excavations" },
  { id:"m11_3", term:"Sloping", definition:"An excavation protection method that cuts back trench walls at a safe angle based on soil type to prevent cave-in. No workers or equipment work inside the slope.", moduleId:11, moduleName:"Excavations" },
  { id:"m11_4", term:"Shoring", definition:"A system of supports (hydraulic, pneumatic, or timber) installed against trench walls to prevent cave-in. Active protection — resists soil movement.", moduleId:11, moduleName:"Excavations" },
  { id:"m11_5", term:"Trench Box (Shield)", definition:"A prefabricated steel or aluminum structure that protects workers inside an excavation. Does not prevent cave-in but shields workers if collapse occurs.", moduleId:11, moduleName:"Excavations" },
  { id:"m11_6", term:"Competent Person (Excavation)", definition:"Required on all excavation projects. Must classify soil, design or select protective systems, inspect the excavation before each shift, and have authority to stop work.", moduleId:11, moduleName:"Excavations" },
  { id:"m11_7", term:"Benching", definition:"An excavation protection method that creates step-shaped horizontal cuts in trench walls. Allowed only in Type A or B soil — NEVER in Type C soil.", moduleId:11, moduleName:"Excavations" },
  { id:"m11_8", term:"Spoil Pile", definition:"Excavated soil placed near the trench opening. Must be kept at least 2 feet from the trench edge to prevent surcharge loading and reduce cave-in risk.", moduleId:11, moduleName:"Excavations" },
  { id:"m11_9", term:"Atmospheric Testing (Excavation)", definition:"Required in all excavations 4 feet or deeper where a hazardous atmosphere could exist. Test order: oxygen → flammable gases → toxic substances.", moduleId:11, moduleName:"Excavations" },

  /* ── Module 12: Cranes & Rigging ── */
  { id:"m12_1", term:"Qualified Rigger", definition:"A person who, due to training and experience, is capable of rigging equipment safely. Must be used for all rigging activities when workers are in the fall zone of the load.", moduleId:12, moduleName:"Cranes" },
  { id:"m12_2", term:"Load Chart", definition:"A manufacturer-provided table or graph showing a crane's safe lifting capacity at various boom lengths, angles, and radii. Must be in the cab and used for every lift.", moduleId:12, moduleName:"Cranes" },
  { id:"m12_3", term:"Rope Lay", definition:"One complete helical cycle of a wire rope's outer wires around the core. Used to measure broken wire removal criteria: ≥6 broken wires per lay requires removal from service.", moduleId:12, moduleName:"Cranes" },
  { id:"m12_4", term:"Bird Cage", definition:"A serious wire rope defect where the rope's strands separate outward, resembling a bird cage. Requires immediate removal from service.", moduleId:12, moduleName:"Cranes" },
  { id:"m12_5", term:"Multiple Lift Rigging", definition:"Lifting more than one structural member at a time with a single crane hook (Christmas tree lift). Maximum of 5 members per lift; requires a qualified rigger and pre-lift meeting.", moduleId:12, moduleName:"Cranes" },
  { id:"m12_6", term:"Sling Angle", definition:"The angle of a rigging sling from vertical. As angle increases, the force on each leg increases dramatically. At 30° from vertical, each leg carries 200% of the load weight.", moduleId:12, moduleName:"Cranes" },
  { id:"m12_7", term:"Signal Person", definition:"A qualified individual who gives signals to a crane operator. Only one signal person may direct the crane at a time. Emergency stop signals from anyone must be obeyed.", moduleId:12, moduleName:"Cranes" },
  { id:"m12_8", term:"NCCCO", definition:"National Commission for the Certification of Crane Operators — the primary accredited crane operator testing organization recognized by OSHA for operator certification.", moduleId:12, moduleName:"Cranes" },

  /* ── Module 13: Tools ── */
  { id:"m13_1", term:"Ring Test", definition:"A pre-use inspection for abrasive wheels: suspend the wheel and tap with a non-metallic object. A clear ring = sound wheel. A dull thud = cracked wheel; do not use.", moduleId:13, moduleName:"Tools" },
  { id:"m13_2", term:"Anti-Kickback Pawls", definition:"Mechanical fingers on a table or circular saw that grip the wood and prevent the saw from being thrown back toward the operator when kickback occurs.", moduleId:13, moduleName:"Tools" },
  { id:"m13_3", term:"Powder-Actuated Tool (PAT)", definition:"A fastening tool that uses an explosive powder cartridge to drive fasteners into hard materials. Requires specific operator training and certification.", moduleId:13, moduleName:"Tools" },
  { id:"m13_4", term:"Hose Whip", definition:"The dangerous flailing of a pressurized pneumatic hose when a connection comes loose. Prevented by securing all connections with safety wires, chains, or retainers.", moduleId:13, moduleName:"Tools" },
  { id:"m13_5", term:"Angle Grinder Guard", definition:"A protective shield that must cover at least 50% of the abrasive disc at all times. Must be adjustable and in place during operation.", moduleId:13, moduleName:"Tools" },
  { id:"m13_6", term:"Splitter / Riving Knife", definition:"A blade-aligned metal piece behind a circular saw blade that keeps the kerf open and prevents the wood from pinching the blade, reducing kickback risk.", moduleId:13, moduleName:"Tools" },
  { id:"m13_7", term:"Maximum RPM Rating", definition:"The speed rating stamped on every abrasive wheel. The wheel must never be operated above this speed — exceeding it risks catastrophic disintegration.", moduleId:13, moduleName:"Tools" },

  /* ── Module 14: Materials Handling ── */
  { id:"m14_1", term:"NIOSH RWL", definition:"NIOSH Recommended Weight Limit — the maximum safe manual lift weight under ideal conditions: 51 lbs. Decreases significantly with awkward posture, reach, or frequency.", moduleId:14, moduleName:"Materials Handling" },
  { id:"m14_2", term:"Safety Can", definition:"An approved container for storing flammable liquids. Must be FM- or UL-listed, have a self-closing lid, and include a flame arrestor screen in the vent.", moduleId:14, moduleName:"Materials Handling" },
  { id:"m14_3", term:"Oxygen/Fuel Separation", definition:"Oxygen and fuel gas cylinders must be stored at least 20 feet apart, or separated by a fire-resistant barrier at least 5 feet high, to prevent simultaneous fire involvement.", moduleId:14, moduleName:"Materials Handling" },
  { id:"m14_4", term:"Forklift Tip-Over", definition:"The leading cause of forklift fatalities. Prevented by: keeping forks low (6–10 in.) when traveling, tilting load back, never taking turns at speed with elevated loads.", moduleId:14, moduleName:"Materials Handling" },
  { id:"m14_5", term:"Valve Protection Cap", definition:"A threaded metal cap that protects the cylinder valve on a compressed gas cylinder. Must be in place whenever a regulator is not attached.", moduleId:14, moduleName:"Materials Handling" },
  { id:"m14_6", term:"Cylinder Cart", definition:"A wheeled device for transporting compressed gas cylinders. Cylinders must never be dragged, rolled on their side, or carried by their valve — always use a cart.", moduleId:14, moduleName:"Materials Handling" },

  /* ── Module 15: Concrete & Masonry ── */
  { id:"m15_1", term:"Formwork", definition:"Temporary molds that shape and support wet concrete during placement and curing. Must be designed by a qualified person to support wet concrete weight (~150 lbs/ft³).", moduleId:15, moduleName:"Concrete" },
  { id:"m15_2", term:"Reshoring", definition:"A temporary support system installed after original formwork is removed in multi-story construction, to support loads until concrete achieves design strength.", moduleId:15, moduleName:"Concrete" },
  { id:"m15_3", term:"Limited Access Zone (LAZ)", definition:"A restricted zone established on the unscaffolded side of a masonry wall under construction. Width = wall height + 4 feet, running the entire wall length.", moduleId:15, moduleName:"Concrete" },
  { id:"m15_4", term:"Cement Dermatitis", definition:"A chemical skin condition caused by prolonged contact with wet cement (pH ~12.5). Can cause severe alkali burns, often painless initially. Prevented by gloves and protective clothing.", moduleId:15, moduleName:"Concrete" },
  { id:"m15_5", term:"Lift Slab Construction", definition:"A method where concrete floor slabs are cast at grade and lifted (jacked) to their final elevation. Requires PE-designed jacking and workers must not be on or below slabs being lifted.", moduleId:15, moduleName:"Concrete" },
  { id:"m15_6", term:"Local Exhaust Ventilation (LEV)", definition:"A dust/fume control system that captures contaminants at the source (e.g., a HEPA vacuum attached to a masonry saw blade). More effective than general ventilation or respirators alone.", moduleId:15, moduleName:"Concrete" },

  /* ── Module 16: Steel Erection ── */
  { id:"m16_1", term:"SSEP", definition:"Site-Specific Erection Plan — a written plan developed before steel erection begins covering the sequence, fall protection, crane positions, rigging, communication, and other site factors.", moduleId:16, moduleName:"Steel Erection" },
  { id:"m16_2", term:"Controlled Decking Zone (CDZ)", definition:"A designated area in steel erection where trained connectors may install metal decking without conventional fall protection. Max width: 90 feet; max advance: 30 feet ahead of leading edge.", moduleId:16, moduleName:"Steel Erection" },
  { id:"m16_3", term:"Connector", definition:"An ironworker who connects structural steel members. Subject to special fall protection rules — must have two means of fall protection when working 15–30 feet above lower levels.", moduleId:16, moduleName:"Steel Erection" },
  { id:"m16_4", term:"Anchor Bolt (Steel)", definition:"Bolts embedded in concrete that secure a steel column's base plate. Minimum of 4 anchor bolts per column must be installed and tightened before the crane releases the column.", moduleId:16, moduleName:"Steel Erection" },
  { id:"m16_5", term:"Safety Deck", definition:"A temporary deck installed below active steel erection to catch workers or falling objects. Required when workers are more than 30 feet above the last completed deck.", moduleId:16, moduleName:"Steel Erection" },
  { id:"m16_6", term:"Subpart R", definition:"29 CFR 1926 Subpart R — the OSHA standard specifically governing steel erection in construction. Covers fall protection, anchor bolts, multi-lift rigging, decking, and more.", moduleId:16, moduleName:"Steel Erection" },

  /* ── Module 17: Fire Protection ── */
  { id:"m17_1", term:"Fire Triangle", definition:"The three elements required for fire: Fuel (combustible material), Oxygen (at least 16%), and Heat (ignition energy). Removing any one element extinguishes or prevents fire.", moduleId:17, moduleName:"Fire Protection" },
  { id:"m17_2", term:"Class B Fire", definition:"A fire involving flammable or combustible liquids and gases (gasoline, oil, propane, paint thinner). Never use water — it spreads burning liquid. Use ABC dry chemical or CO₂.", moduleId:17, moduleName:"Fire Protection" },
  { id:"m17_3", term:"PASS Technique", definition:"The correct way to use a fire extinguisher: Pull the pin → Aim at the BASE of the fire → Squeeze the handle → Sweep side to side across the base.", moduleId:17, moduleName:"Fire Protection" },
  { id:"m17_4", term:"Fire Watch", definition:"A trained person stationed to monitor for fire during and for at least 30 minutes after hot work (welding, cutting, grinding). Must have extinguishing equipment readily available.", moduleId:17, moduleName:"Fire Protection" },
  { id:"m17_5", term:"Hot Work Permit", definition:"Written authorization to perform operations (welding, cutting, brazing) that produce sparks or heat. Specifies location, duration, hazards, and required precautions.", moduleId:17, moduleName:"Fire Protection" },
  { id:"m17_6", term:"Flash Point", definition:"The lowest temperature at which a flammable liquid produces enough vapor to ignite momentarily when exposed to an ignition source. Lower flash point = greater fire hazard.", moduleId:17, moduleName:"Fire Protection" },
  { id:"m17_7", term:"Class C Fire", definition:"A fire involving energized electrical equipment. De-energize the equipment first if safe to do so, then treat as Class A or B. Never use water on energized electrical fires.", moduleId:17, moduleName:"Fire Protection" },

  /* ── Module 18: Welding & Cutting ── */
  { id:"m18_1", term:"Arc Eye (Welder's Flash)", definition:"A painful UV-induced corneal injury (photokeratitis) caused by viewing an arc without proper eye protection. Symptoms: pain, sensitivity to light, and a gritty feeling — appear hours later.", moduleId:18, moduleName:"Welding" },
  { id:"m18_2", term:"Lens Shade Number", definition:"A rating indicating how much light a welding lens filters. Higher number = darker lens. Minimum shade #10 for arc welding (SMAW/GMAW); higher amperages require #12–#14.", moduleId:18, moduleName:"Welding" },
  { id:"m18_3", term:"Metal Fume Fever", definition:"A flu-like illness caused by inhaling zinc oxide fumes from welding on galvanized steel. Symptoms: chills, fever, nausea — usually resolve within 24–48 hours. Repeated exposure may cause lasting damage.", moduleId:18, moduleName:"Welding" },
  { id:"m18_4", term:"15 PSI Rule (Acetylene)", definition:"Acetylene must never be used at pressures above 15 psi. Above this, the gas can decompose explosively without oxygen present.", moduleId:18, moduleName:"Welding" },
  { id:"m18_5", term:"Oxy-Fuel Welding/Cutting", definition:"A process using compressed oxygen and a fuel gas (acetylene, propane) to produce a flame for welding or cutting. Fire and explosion hazards from cylinder storage and hose/regulator leaks.", moduleId:18, moduleName:"Welding" },
  { id:"m18_6", term:"Cadmium Fumes", definition:"Highly toxic fumes released when welding or cutting cadmium-coated metals. Even brief exposure can cause acute kidney damage and pulmonary edema. Long-term exposure is carcinogenic.", moduleId:18, moduleName:"Welding" },
  { id:"m18_7", term:"Fire Watch (Welding)", definition:"Required during all welding/cutting and for at least 30 minutes after work stops. The fire watch has no other duties and must have extinguishing equipment immediately available.", moduleId:18, moduleName:"Welding" },

  /* ── Module 19: Motor Vehicles ── */
  { id:"m19_1", term:"ROPS", definition:"Rollover Protective Structure — a cab or frame designed to prevent the operator from being crushed if equipment tips over. Required on most earthmoving equipment. Seatbelts must be worn.", moduleId:19, moduleName:"Motor Vehicles" },
  { id:"m19_2", term:"FOPS", definition:"Falling Object Protective Structure — overhead protection on equipment cabs that shields operators from objects falling from above (required at demolition sites, logging, etc.).", moduleId:19, moduleName:"Motor Vehicles" },
  { id:"m19_3", term:"Pre-Operation Inspection", definition:"A mandatory check of all safety systems (brakes, steering, lights, horn, backup alarm, seatbelt, ROPS, tires, fluids) before each shift. Equipment with safety defects must be removed from service.", moduleId:19, moduleName:"Motor Vehicles" },
  { id:"m19_4", term:"Aerial Lift PFAS Rule", definition:"Workers in boom-type aerial lifts must wear PFAS anchored to the basket or boom — NOT to an adjacent structure. Anchoring to a structure risks ejection if the lift moves.", moduleId:19, moduleName:"Motor Vehicles" },
  { id:"m19_5", term:"Forklift Re-evaluation", definition:"OSHA requires forklift operators to be evaluated on their performance at least every 3 years, and retrained after accidents, near-misses, unsafe operation, or assignment to a different truck type.", moduleId:19, moduleName:"Motor Vehicles" },
  { id:"m19_6", term:"No Riders Rule", definition:"Workers may only ride as passengers on equipment when a seat designed for a passenger (with seatbelt) is provided. Riding on fenders, forks, buckets, or steps is prohibited.", moduleId:19, moduleName:"Motor Vehicles" },

  /* ── Module 20: Confined Spaces ── */
  { id:"m20_1", term:"Permit-Required Confined Space", definition:"A confined space that contains or may contain: a hazardous atmosphere, engulfment hazard, internal entrapment geometry, or any other recognized serious safety/health hazard.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_2", term:"Authorized Entrant", definition:"A worker trained and permitted to enter a confined space. Must know the hazards, signs of exposure, and how and when to self-rescue or call for help.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_3", term:"Attendant", definition:"The confined space safety role stationed OUTSIDE at all times. Monitors entrants, tracks how many are inside, maintains communication, and summons rescue. Must NEVER enter to rescue.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_4", term:"Entry Supervisor", definition:"The person who authorizes confined space entry after verifying all permit conditions are met. Cancels the permit if conditions change.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_5", term:"Oxygen Deficiency", definition:"An atmosphere with less than 19.5% oxygen. Hazardous atmosphere — entry prohibited without supplied-air respiratory protection. Below 16%, loss of consciousness can occur rapidly.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_6", term:"LEL", definition:"Lower Explosive Limit — the minimum concentration of a flammable gas/vapor in air required for ignition. >10% LEL = hazardous atmosphere; >25% LEL = evacuate immediately.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_7", term:"Non-Entry Rescue", definition:"The preferred confined space rescue method using a retrieval system (lifeline, harness, mechanical advantage device) to extract a worker without anyone else entering the space.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_8", term:"Atmospheric Testing Order", definition:"The required sequence for confined space air testing: 1) Oxygen first (prevents false meter readings), 2) Flammable gases, 3) Toxic substances.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_9", term:"Oxygen Enrichment", definition:"An atmosphere with more than 23.5% oxygen. Dramatically increases flammability of materials — a cigarette or spark can ignite clothing or hair. Entry requires careful atmospheric controls.", moduleId:20, moduleName:"Confined Spaces" },
  { id:"m20_10", term:"Entry Permit", definition:"A written document that authorizes confined space entry. Must specify: space to be entered, work to be done, date/duration, hazards, controls, test results, rescue plan, and names of all roles.", moduleId:20, moduleName:"Confined Spaces" }
];
